export const AUTH_SUCCESS = 'LOG_IN_SUCCESS';
export const AUTH_FAILURE = 'LOG_IN_FAILURE';
export const UNAUTH = 'UNAUTH';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_WITH_REPLACEMENT= 'FETCH_PRODUCTS_WITH_REPLACEMENT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const CHANGE_FILTER = 'CHANGE_FILTER';
export const RESET_FILTER = 'RESET_FILTER';
export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';

export const SET_ROLE = 'SET_ROLE';